/*
 * Laendertabelle — Datenteil.
 *
 * Herkunft: ISO 3166-1 aus Wikidata (Alpha-2, Alpha-3, deutscher Name, GND-ID),
 * dazu untergegangene Staaten und die in Archivlisten ueblichen Kurzformen.
 * Uebernommen aus dem PHP-Stand (html/data/countries.json) und unveraendert
 * weitergefuehrt, damit bestehende Profile dieselben Namen erhalten.
 *
 * Kein Dienst zur Laufzeit: Die Tabelle liegt im Repo, Haeuser koennen eigene
 * Schreibweisen ueber COUNTRY_EXTRA (countries.ts) nachtragen.
 */

export interface CountryEntry {
  /** ISO 3166-1 Alpha-3 bzw. Kuerzel des historischen Staates. */
  code: string
  /** ISO 3166-1 Alpha-2, falls vorhanden. */
  alpha2: string
  /** Deutscher Name — der Wert, den der Konverter ausgibt. */
  name: string
  /** GND-ID des Landes; wandert ueber den Anreicherungskanal mit. */
  gnd: string
  /** Untergegangener Staat (DDR, CSSR, Sowjetunion …). */
  historic: boolean
}

export const COUNTRY_ENTRIES: readonly CountryEntry[] = [
  { code: 'ABW', alpha2: 'AW', name: 'Aruba', gnd: '4079840-9', historic: false },
  { code: 'AFG', alpha2: 'AF', name: 'Afghanistan', gnd: '4000687-6', historic: false },
  { code: 'AFI', alpha2: '', name: 'Französisches Afar- und Issa-Territorium', gnd: '14491-5', historic: false },
  { code: 'AGO', alpha2: 'AO', name: 'Angola', gnd: '4002050-2', historic: false },
  { code: 'AIA', alpha2: 'AI', name: 'Anguilla', gnd: '4426211-5', historic: false },
  { code: 'ALA', alpha2: 'AX', name: 'Åland', gnd: '4079677-2', historic: false },
  { code: 'ALB', alpha2: 'AL', name: 'Albanien', gnd: '4001028-4', historic: false },
  { code: 'AND', alpha2: 'AD', name: 'Andorra', gnd: '4001937-8', historic: false },
  { code: 'ANT', alpha2: 'AN', name: 'Niederländische Antillen', gnd: '4101202-1', historic: false },
  { code: 'ARE', alpha2: 'AE', name: 'Vereinigte Arabische Emirate', gnd: '4062742-1', historic: false },
  { code: 'ARG', alpha2: 'AR', name: 'Argentinien', gnd: '4002890-2', historic: false },
  { code: 'ARM', alpha2: 'AM', name: 'Armenien', gnd: '4085931-9', historic: false },
  { code: 'ASM', alpha2: 'AS', name: 'Amerikanisch-Samoa', gnd: '4085684-7', historic: false },
  { code: 'ATA', alpha2: 'AQ', name: 'Antarktika', gnd: '4192069-7', historic: false },
  { code: 'ATB', alpha2: '', name: 'Britisches Antarktis-Territorium', gnd: '4399981-5', historic: false },
  { code: 'ATF', alpha2: 'TF', name: 'Französische Süd- und Antarktisgebiete', gnd: '4450787-2', historic: false },
  { code: 'ATG', alpha2: 'AG', name: 'Antigua und Barbuda', gnd: '4086593-9', historic: false },
  { code: 'ATN', alpha2: '', name: 'Königin-Maud-Land', gnd: '4393524-2', historic: false },
  { code: 'AUS', alpha2: 'AU', name: 'Australien', gnd: '4003900-6', historic: false },
  { code: 'AUT', alpha2: 'AT', name: 'Österreich', gnd: '4043271-3', historic: false },
  { code: 'AZE', alpha2: 'AZ', name: 'Aserbaidschan', gnd: '4068887-2', historic: false },
  { code: 'BDI', alpha2: 'BI', name: 'Burundi', gnd: '4009181-8', historic: false },
  { code: 'BEL', alpha2: 'BE', name: 'Belgien', gnd: '4005406-8', historic: false },
  { code: 'BEN', alpha2: 'BJ', name: 'Benin', gnd: '4005503-6', historic: false },
  { code: 'BES', alpha2: 'BQ', name: 'Karibische Niederlande', gnd: '', historic: false },
  { code: 'BFA', alpha2: 'BF', name: 'Burkina Faso', gnd: '4088707-8', historic: false },
  { code: 'BGD', alpha2: 'BD', name: 'Bangladesch', gnd: '4130903-0', historic: false },
  { code: 'BGR', alpha2: 'BG', name: 'Bulgarien', gnd: '4008866-2', historic: false },
  { code: 'BHR', alpha2: 'BH', name: 'Bahrain', gnd: '4004268-6', historic: false },
  { code: 'BHS', alpha2: 'BS', name: 'Bahamas', gnd: '4069081-7', historic: false },
  { code: 'BIH', alpha2: 'BA', name: 'Bosnien und Herzegowina', gnd: '4088119-2', historic: false },
  { code: 'BLM', alpha2: 'BL', name: 'Saint-Barthélemy', gnd: '4271726-7', historic: false },
  { code: 'BLR', alpha2: 'BY', name: 'Belarus', gnd: '4079143-9', historic: false },
  { code: 'BLZ', alpha2: 'BZ', name: 'Belize', gnd: '4005412-3', historic: false },
  { code: 'BMU', alpha2: 'BM', name: 'Bermuda', gnd: '4005759-8', historic: false },
  { code: 'BOL', alpha2: 'BO', name: 'Bolivien', gnd: '4007607-6', historic: false },
  { code: 'BRA', alpha2: 'BR', name: 'Brasilien', gnd: '4008003-1', historic: false },
  { code: 'BRB', alpha2: 'BB', name: 'Barbados', gnd: '4004487-7', historic: false },
  { code: 'BRN', alpha2: 'BN', name: 'Brunei', gnd: '4008479-6', historic: false },
  { code: 'BTN', alpha2: 'BT', name: 'Bhutan', gnd: '4006397-5', historic: false },
  { code: 'BVT', alpha2: 'BV', name: 'Bouvetinsel', gnd: '4450775-6', historic: false },
  { code: 'BWA', alpha2: 'BW', name: 'Botswana', gnd: '4007857-7', historic: false },
  { code: 'BYS', alpha2: '', name: 'Belarussische Sozialistische Sowjetrepublik', gnd: '1009143-9', historic: false },
  { code: 'CAF', alpha2: 'CF', name: 'Zentralafrikanische Republik', gnd: '4067608-0', historic: false },
  { code: 'CAN', alpha2: 'CA', name: 'Kanada', gnd: '4029456-0', historic: false },
  { code: 'CCK', alpha2: 'CC', name: 'Kokosinseln', gnd: '4298716-7', historic: false },
  { code: 'CHE', alpha2: 'CH', name: 'Schweiz', gnd: '4053881-3', historic: false },
  { code: 'CHL', alpha2: 'CL', name: 'Chile', gnd: '4009929-5', historic: false },
  { code: 'CHN', alpha2: 'CN', name: 'Volksrepublik China', gnd: '4009937-4', historic: false },
  { code: 'CIV', alpha2: 'CI', name: 'Elfenbeinküste', gnd: '4014426-4', historic: false },
  { code: 'CMR', alpha2: 'CM', name: 'Kamerun', gnd: '4029413-4', historic: false },
  { code: 'COD', alpha2: 'CD', name: 'Demokratische Republik Kongo', gnd: '4067357-1', historic: false },
  { code: 'COG', alpha2: 'CG', name: 'Republik Kongo', gnd: '4032097-2', historic: false },
  { code: 'COK', alpha2: 'CK', name: 'Cookinseln', gnd: '4230226-2', historic: false },
  { code: 'COL', alpha2: 'CO', name: 'Kolumbien', gnd: '4031812-6', historic: false },
  { code: 'COM', alpha2: 'KM', name: 'Komoren', gnd: '4265797-0', historic: false },
  { code: 'CPV', alpha2: 'CV', name: 'Kap Verde', gnd: '4029617-9', historic: false },
  { code: 'CRI', alpha2: 'CR', name: 'Costa Rica', gnd: '4010618-4', historic: false },
  { code: 'CRQ', alpha2: 'CQ', name: 'Sark', gnd: '4105354-0', historic: false },
  { code: 'CSK', alpha2: '', name: 'Tschechoslowakei', gnd: '4078435-6', historic: true },
  { code: 'CTE', alpha2: '', name: 'Kanton und Enderbury', gnd: '', historic: false },
  { code: 'CUB', alpha2: 'CU', name: 'Kuba', gnd: '4033340-1', historic: false },
  { code: 'CUW', alpha2: 'CW', name: 'Curaçao', gnd: '4010774-7', historic: false },
  { code: 'CXR', alpha2: 'CX', name: 'Weihnachtsinsel', gnd: '4219436-2', historic: false },
  { code: 'CYM', alpha2: 'KY', name: 'Cayman Islands', gnd: '4310479-4', historic: false },
  { code: 'CYP', alpha2: 'CY', name: 'Zypern', gnd: '4079596-2', historic: false },
  { code: 'CZE', alpha2: 'CZ', name: 'Tschechien', gnd: '4303381-7', historic: false },
  { code: 'DDR', alpha2: 'DD', name: 'Deutsche Demokratische Republik', gnd: '4011890-3', historic: true },
  { code: 'DEU', alpha2: 'DE', name: 'Deutschland', gnd: '4011882-4', historic: false },
  { code: 'DHY', alpha2: '', name: 'Republik Dahomey', gnd: '15582-2', historic: false },
  { code: 'DJI', alpha2: 'DJ', name: 'Dschibuti', gnd: '4070610-2', historic: false },
  { code: 'DMA', alpha2: 'DM', name: 'Dominica', gnd: '4085456-5', historic: false },
  { code: 'DNK', alpha2: 'DK', name: 'Dänemark', gnd: '4010877-6', historic: false },
  { code: 'DOM', alpha2: 'DO', name: 'Dominikanische Republik', gnd: '4012694-8', historic: false },
  { code: 'DZA', alpha2: 'DZ', name: 'Algerien', gnd: '4001179-3', historic: false },
  { code: 'ECU', alpha2: 'EC', name: 'Ecuador', gnd: '4129321-6', historic: false },
  { code: 'EGY', alpha2: 'EG', name: 'Ägypten', gnd: '4000556-2', historic: false },
  { code: 'ERI', alpha2: 'ER', name: 'Eritrea', gnd: '4015278-9', historic: false },
  { code: 'ESH', alpha2: 'EH', name: 'Westsahara', gnd: '4289787-7', historic: false },
  { code: 'ESP', alpha2: 'ES', name: 'Spanien', gnd: '4055964-6', historic: false },
  { code: 'EST', alpha2: 'EE', name: 'Estland', gnd: '4015587-0', historic: false },
  { code: 'ETH', alpha2: 'ET', name: 'Äthiopien', gnd: '4000639-6', historic: false },
  { code: 'FIN', alpha2: 'FI', name: 'Finnland', gnd: '4017243-0', historic: false },
  { code: 'FJI', alpha2: 'FJ', name: 'Fidschi', gnd: '4017063-9', historic: false },
  { code: 'FLK', alpha2: 'FK', name: 'Falklandinseln', gnd: '4071109-2', historic: false },
  { code: 'FRA', alpha2: 'FR', name: 'Frankreich', gnd: '4018145-5', historic: false },
  { code: 'FRO', alpha2: 'FO', name: 'Färöer', gnd: '4016258-8', historic: false },
  { code: 'FSM', alpha2: 'FM', name: 'Föderierte Staaten von Mikronesien', gnd: '4274661-9', historic: false },
  { code: 'FXX', alpha2: '', name: 'Metropolitan-Frankreich', gnd: '', historic: false },
  { code: 'GAB', alpha2: 'GA', name: 'Gabun', gnd: '4019052-3', historic: false },
  { code: 'GBR', alpha2: 'GB', name: 'Vereinigtes Königreich', gnd: '4022153-2', historic: false },
  { code: 'GEL', alpha2: '', name: 'Gilbert- und Elliceinseln', gnd: '', historic: false },
  { code: 'GEO', alpha2: 'GE', name: 'Georgien', gnd: '4022406-5', historic: false },
  { code: 'GGY', alpha2: 'GG', name: 'Guernsey', gnd: '4022467-3', historic: false },
  { code: 'GHA', alpha2: 'GH', name: 'Ghana', gnd: '4020949-0', historic: false },
  { code: 'GIB', alpha2: 'GI', name: 'Gibraltar', gnd: '4020965-9', historic: false },
  { code: 'GIN', alpha2: 'GN', name: 'Guinea', gnd: '4022520-3', historic: false },
  { code: 'GLP', alpha2: 'GP', name: 'Guadeloupe', gnd: '4086841-2', historic: false },
  { code: 'GMB', alpha2: 'GM', name: 'Gambia', gnd: '4019197-7', historic: false },
  { code: 'GNB', alpha2: 'GW', name: 'Guinea-Bissau', gnd: '4022522-7', historic: false },
  { code: 'GNQ', alpha2: 'GQ', name: 'Äquatorialguinea', gnd: '4068436-2', historic: false },
  { code: 'GRC', alpha2: 'GR', name: 'Griechenland', gnd: '4022047-3', historic: false },
  { code: 'GRD', alpha2: 'GD', name: 'Grenada', gnd: '4021981-1', historic: false },
  { code: 'GRL', alpha2: 'GL', name: 'Grönland', gnd: '4022113-1', historic: false },
  { code: 'GTM', alpha2: 'GT', name: 'Guatemala', gnd: '4022428-4', historic: false },
  { code: 'GUF', alpha2: 'GF', name: 'Französisch-Guayana', gnd: '4018184-4', historic: false },
  { code: 'GUM', alpha2: 'GU', name: 'Guam', gnd: '4094188-7', historic: false },
  { code: 'GUY', alpha2: 'GY', name: 'Guyana', gnd: '4072186-3', historic: false },
  { code: 'HKG', alpha2: 'HK', name: 'Hongkong', gnd: '4025822-1', historic: false },
  { code: 'HMD', alpha2: 'HM', name: 'Heard und McDonaldinseln', gnd: '4451482-7', historic: false },
  { code: 'HND', alpha2: 'HN', name: 'Honduras', gnd: '4025814-2', historic: false },
  { code: 'HRV', alpha2: 'HR', name: 'Kroatien', gnd: '4073841-3', historic: false },
  { code: 'HTI', alpha2: 'HT', name: 'Haiti', gnd: '4022974-9', historic: false },
  { code: 'HUN', alpha2: 'HU', name: 'Ungarn', gnd: '4078541-5', historic: false },
  { code: 'HVO', alpha2: '', name: 'Obervolta', gnd: '', historic: false },
  { code: 'IDN', alpha2: 'ID', name: 'Indonesien', gnd: '4026761-1', historic: false },
  { code: 'IMN', alpha2: 'IM', name: 'Isle of Man', gnd: '4027756-2', historic: false },
  { code: 'IND', alpha2: 'IN', name: 'Indien', gnd: '4026722-2', historic: false },
  { code: 'IOT', alpha2: 'IO', name: 'Britisches Territorium im Indischen Ozean', gnd: '4480858-6', historic: false },
  { code: 'IRL', alpha2: 'IE', name: 'Irland', gnd: '4027667-3', historic: false },
  { code: 'IRN', alpha2: 'IR', name: 'Iran', gnd: '4027653-3', historic: false },
  { code: 'IRQ', alpha2: 'IQ', name: 'Irak', gnd: '4072920-5', historic: false },
  { code: 'ISL', alpha2: 'IS', name: 'Island', gnd: '4027754-9', historic: false },
  { code: 'ISR', alpha2: 'IL', name: 'Israel', gnd: '4027808-6', historic: false },
  { code: 'ITA', alpha2: 'IT', name: 'Italien', gnd: '4027833-5', historic: false },
  { code: 'JAM', alpha2: 'JM', name: 'Jamaika', gnd: '4028456-6', historic: false },
  { code: 'JOR', alpha2: 'JO', name: 'Jordanien', gnd: '4028750-6', historic: false },
  { code: 'JPN', alpha2: 'JP', name: 'Japan', gnd: '4028495-5', historic: false },
  { code: 'JTN', alpha2: '', name: 'Johnston-Atoll', gnd: '', historic: false },
  { code: 'KAZ', alpha2: 'KZ', name: 'Kasachstan', gnd: '4029839-5', historic: false },
  { code: 'KEN', alpha2: 'KE', name: 'Kenia', gnd: '4030236-2', historic: false },
  { code: 'KGZ', alpha2: 'KG', name: 'Kirgisistan', gnd: '4030848-0', historic: false },
  { code: 'KHM', alpha2: 'KH', name: 'Kambodscha', gnd: '4029400-6', historic: false },
  { code: 'KIR', alpha2: 'KI', name: 'Kiribati', gnd: '4073459-6', historic: false },
  { code: 'KNA', alpha2: 'KN', name: 'St. Kitts und Nevis', gnd: '4118251-0', historic: false },
  { code: 'KOR', alpha2: 'KR', name: 'Südkorea', gnd: '4078029-6', historic: false },
  { code: 'KWT', alpha2: 'KW', name: 'Kuwait', gnd: '4073919-3', historic: false },
  { code: 'LAO', alpha2: 'LA', name: 'Laos', gnd: '4034571-3', historic: false },
  { code: 'LBN', alpha2: 'LB', name: 'Libanon', gnd: '4035567-6', historic: false },
  { code: 'LBR', alpha2: 'LR', name: 'Liberia', gnd: '4035583-4', historic: false },
  { code: 'LBY', alpha2: 'LY', name: 'Libyen', gnd: '4035589-5', historic: false },
  { code: 'LCA', alpha2: 'LC', name: 'St. Lucia', gnd: '4051307-5', historic: false },
  { code: 'LIE', alpha2: 'LI', name: 'Liechtenstein', gnd: '4035665-6', historic: false },
  { code: 'LKA', alpha2: 'LK', name: 'Sri Lanka', gnd: '4009696-8', historic: false },
  { code: 'LSO', alpha2: 'LS', name: 'Lesotho', gnd: '4074183-7', historic: false },
  { code: 'LTU', alpha2: 'LT', name: 'Litauen', gnd: '4074266-0', historic: false },
  { code: 'LUX', alpha2: 'LU', name: 'Luxemburg', gnd: '4036728-9', historic: false },
  { code: 'LVA', alpha2: 'LV', name: 'Lettland', gnd: '4074187-4', historic: false },
  { code: 'MAC', alpha2: 'MO', name: 'Macau', gnd: '4036791-5', historic: false },
  { code: 'MAF', alpha2: 'MF', name: 'Saint-Martin', gnd: '4435868-4', historic: false },
  { code: 'MAR', alpha2: 'MA', name: 'Marokko', gnd: '4037680-1', historic: false },
  { code: 'MCO', alpha2: 'MC', name: 'Monaco', gnd: '4040031-1', historic: false },
  { code: 'MDA', alpha2: 'MD', name: 'Moldau', gnd: '4039967-9', historic: false },
  { code: 'MDG', alpha2: 'MG', name: 'Madagaskar', gnd: '4074425-5', historic: false },
  { code: 'MDV', alpha2: 'MV', name: 'Malediven', gnd: '4037212-1', historic: false },
  { code: 'MEX', alpha2: 'MX', name: 'Mexiko', gnd: '4039058-5', historic: false },
  { code: 'MHL', alpha2: 'MH', name: 'Marshallinseln', gnd: '4037700-3', historic: false },
  { code: 'MID', alpha2: '', name: 'Midwayinseln', gnd: '4039148-6', historic: false },
  { code: 'MKD', alpha2: 'MK', name: 'Nordmazedonien', gnd: '4114937-3', historic: false },
  { code: 'MLI', alpha2: 'ML', name: 'Mali', gnd: '4074505-3', historic: false },
  { code: 'MLT', alpha2: 'MT', name: 'Malta', gnd: '4037257-1', historic: false },
  { code: 'MMR', alpha2: 'MM', name: 'Myanmar', gnd: '1193111315', historic: false },
  { code: 'MNE', alpha2: 'ME', name: 'Montenegro', gnd: '4040163-7', historic: false },
  { code: 'MNG', alpha2: 'MN', name: 'Mongolei', gnd: '4040056-6', historic: false },
  { code: 'MNP', alpha2: 'MP', name: 'Nördliche Marianen', gnd: '4249308-0', historic: false },
  { code: 'MOZ', alpha2: 'MZ', name: 'Mosambik', gnd: '4039786-5', historic: false },
  { code: 'MRT', alpha2: 'MR', name: 'Mauretanien', gnd: '4038051-8', historic: false },
  { code: 'MSR', alpha2: 'MS', name: 'Montserrat', gnd: '4274693-0', historic: false },
  { code: 'MTQ', alpha2: 'MQ', name: 'Martinique', gnd: '4037735-0', historic: false },
  { code: 'MUS', alpha2: 'MU', name: 'Mauritius', gnd: '4074641-0', historic: false },
  { code: 'MWI', alpha2: 'MW', name: 'Malawi', gnd: '4074495-4', historic: false },
  { code: 'MYS', alpha2: 'MY', name: 'Malaysia', gnd: '4037203-0', historic: false },
  { code: 'MYT', alpha2: 'YT', name: 'Mayotte', gnd: '6106489-0', historic: false },
  { code: 'NAM', alpha2: 'NA', name: 'Namibia', gnd: '4075202-1', historic: false },
  { code: 'NCL', alpha2: 'NC', name: 'Neukaledonien', gnd: '4102498-9', historic: false },
  { code: 'NER', alpha2: 'NE', name: 'Niger', gnd: '4042298-7', historic: false },
  { code: 'NFK', alpha2: 'NF', name: 'Norfolkinsel', gnd: '4294928-2', historic: false },
  { code: 'NGA', alpha2: 'NG', name: 'Nigeria', gnd: '4042300-1', historic: false },
  { code: 'NHB', alpha2: '', name: 'Kondominium Neue Hebriden', gnd: '61014-8', historic: false },
  { code: 'NIC', alpha2: 'NI', name: 'Nicaragua', gnd: '4042050-4', historic: false },
  { code: 'NIU', alpha2: 'NU', name: 'Niue', gnd: '4293521-0', historic: false },
  { code: 'NLD', alpha2: 'NL', name: 'Niederlande', gnd: '4042203-3', historic: false },
  { code: 'NOR', alpha2: 'NO', name: 'Norwegen', gnd: '4042640-3', historic: false },
  { code: 'NPL', alpha2: 'NP', name: 'Nepal', gnd: '4041612-4', historic: false },
  { code: 'NRU', alpha2: 'NR', name: 'Naoero', gnd: '4122008-0', historic: false },
  { code: 'NZL', alpha2: 'NZ', name: 'Neuseeland', gnd: '4041915-0', historic: false },
  { code: 'OMN', alpha2: 'OM', name: 'Oman', gnd: '4075653-1', historic: false },
  { code: 'PAK', alpha2: 'PK', name: 'Pakistan', gnd: '4075812-6', historic: false },
  { code: 'PAN', alpha2: 'PA', name: 'Panama', gnd: '4044445-4', historic: false },
  { code: 'PCI', alpha2: 'PC', name: 'Treuhandgebiet Pazifische Inseln', gnd: '', historic: false },
  { code: 'PCN', alpha2: 'PN', name: 'Pitcairninseln', gnd: '4115982-2', historic: false },
  { code: 'PER', alpha2: 'PE', name: 'Peru', gnd: '4045312-1', historic: false },
  { code: 'PHL', alpha2: 'PH', name: 'Philippinen', gnd: '4045771-0', historic: false },
  { code: 'PLW', alpha2: 'PW', name: 'Palau', gnd: '4044396-6', historic: false },
  { code: 'PNG', alpha2: 'PG', name: 'Papua-Neuguinea', gnd: '4044569-0', historic: false },
  { code: 'POL', alpha2: 'PL', name: 'Polen', gnd: '4046496-9', historic: false },
  { code: 'PRI', alpha2: 'PR', name: 'Puerto Rico', gnd: '4076429-1', historic: false },
  { code: 'PRK', alpha2: 'KP', name: 'Nordkorea', gnd: '4075468-6', historic: false },
  { code: 'PRT', alpha2: 'PT', name: 'Portugal', gnd: '4046843-4', historic: false },
  { code: 'PRY', alpha2: 'PY', name: 'Paraguay', gnd: '4044601-3', historic: false },
  { code: 'PSE', alpha2: '', name: 'Palästinensische Autonomiegebiete', gnd: '4448806-3', historic: false },
  { code: 'PYF', alpha2: 'PF', name: 'Französisch-Polynesien', gnd: '4018191-1', historic: false },
  { code: 'QAT', alpha2: 'QA', name: 'Katar', gnd: '4029924-7', historic: false },
  { code: 'REU', alpha2: 'RE', name: 'Réunion', gnd: '4049639-9', historic: false },
  { code: 'ROU', alpha2: 'RO', name: 'Rumänien', gnd: '4050939-4', historic: false },
  { code: 'RUS', alpha2: 'RU', name: 'Russland', gnd: '4076899-5', historic: false },
  { code: 'RWA', alpha2: 'RW', name: 'Ruanda', gnd: '4076910-0', historic: false },
  { code: 'SAU', alpha2: 'SA', name: 'Saudi-Arabien', gnd: '4051788-3', historic: false },
  { code: 'SCG', alpha2: '', name: 'Serbien und Montenegro', gnd: '4692332-9', historic: false },
  { code: 'SDN', alpha2: 'SD', name: 'Sudan', gnd: '4058378-8', historic: false },
  { code: 'SEN', alpha2: 'SN', name: 'Senegal', gnd: '4054529-5', historic: false },
  { code: 'SGP', alpha2: 'SG', name: 'Singapur', gnd: '4055089-8', historic: false },
  { code: 'SGS', alpha2: 'GS', name: 'Südgeorgien und die Südlichen Sandwichinseln', gnd: '4451507-8', historic: false },
  { code: 'SHN', alpha2: 'SH', name: 'St. Helena, Ascension und Tristan da Cunha', gnd: '4051605-2', historic: false },
  { code: 'SJM', alpha2: 'SJ', name: 'Svalbard und Jan Mayen', gnd: '', historic: false },
  { code: 'SLB', alpha2: 'SB', name: 'Salomonen', gnd: '4265796-9', historic: false },
  { code: 'SLE', alpha2: 'SL', name: 'Sierra Leone', gnd: '4054908-2', historic: false },
  { code: 'SLV', alpha2: 'SV', name: 'El Salvador', gnd: '4014499-9', historic: false },
  { code: 'SMR', alpha2: 'SM', name: 'San Marino', gnd: '4051524-2', historic: false },
  { code: 'SOM', alpha2: 'SO', name: 'Somalia', gnd: '4077509-4', historic: false },
  { code: 'SPM', alpha2: 'PM', name: 'Saint-Pierre und Miquelon', gnd: '4198311-7', historic: false },
  { code: 'SRB', alpha2: 'RS', name: 'Serbien', gnd: '4054598-2', historic: false },
  { code: 'SSD', alpha2: 'SS', name: 'Südsudan', gnd: '7755222-2', historic: false },
  { code: 'STP', alpha2: 'ST', name: 'São Tomé und Príncipe', gnd: '4118426-9', historic: false },
  { code: 'SUN', alpha2: '', name: 'Sowjetunion', gnd: '4077548-3', historic: true },
  { code: 'SUR', alpha2: 'SR', name: 'Suriname', gnd: '4058664-9', historic: false },
  { code: 'SVK', alpha2: 'SK', name: 'Slowakei', gnd: '4055297-4', historic: false },
  { code: 'SVN', alpha2: 'SI', name: 'Slowenien', gnd: '4055302-4', historic: false },
  { code: 'SWE', alpha2: 'SE', name: 'Schweden', gnd: '4077258-5', historic: false },
  { code: 'SWZ', alpha2: 'SZ', name: 'Eswatini', gnd: '1225128579', historic: false },
  { code: 'SXM', alpha2: 'SX', name: 'Sint Maarten', gnd: '7589556-0', historic: false },
  { code: 'SYC', alpha2: 'SC', name: 'Seychellen', gnd: '4054694-9', historic: false },
  { code: 'SYR', alpha2: 'SY', name: 'Syrien', gnd: '4058794-0', historic: false },
  { code: 'TCA', alpha2: 'TC', name: 'Turks- und Caicosinseln', gnd: '4285170-1', historic: false },
  { code: 'TCD', alpha2: 'TD', name: 'Tschad', gnd: '4061074-3', historic: false },
  { code: 'TGO', alpha2: 'TG', name: 'Togo', gnd: '4060344-1', historic: false },
  { code: 'THA', alpha2: 'TH', name: 'Thailand', gnd: '4078228-1', historic: false },
  { code: 'TJK', alpha2: 'TJ', name: 'Tadschikistan', gnd: '4058877-4', historic: false },
  { code: 'TKL', alpha2: 'TK', name: 'Tokelau', gnd: '4236941-1', historic: false },
  { code: 'TKM', alpha2: 'TM', name: 'Turkmenistan', gnd: '4061255-7', historic: false },
  { code: 'TLS', alpha2: 'TL', name: 'Osttimor', gnd: '4075765-1', historic: false },
  { code: 'TON', alpha2: 'TO', name: 'Tonga', gnd: '4060396-9', historic: false },
  { code: 'TTO', alpha2: 'TT', name: 'Trinidad und Tobago', gnd: '4060907-8', historic: false },
  { code: 'TUN', alpha2: 'TN', name: 'Tunesien', gnd: '4061206-5', historic: false },
  { code: 'TUR', alpha2: 'TR', name: 'Türkei', gnd: '4061163-2', historic: false },
  { code: 'TUV', alpha2: 'TV', name: 'Tuvalu', gnd: '4107331-9', historic: false },
  { code: 'TWN', alpha2: 'TW', name: 'Republik China', gnd: '4017875-4', historic: false },
  { code: 'TZA', alpha2: 'TZ', name: 'Tansania', gnd: '4078149-5', historic: false },
  { code: 'UGA', alpha2: 'UG', name: 'Uganda', gnd: '4061457-8', historic: false },
  { code: 'UKR', alpha2: 'UA', name: 'Ukraine', gnd: '4061496-7', historic: false },
  { code: 'UMI', alpha2: 'UM', name: 'Kleinere Amerikanische Überseeinseln', gnd: '4451497-9', historic: false },
  { code: 'URY', alpha2: 'UY', name: 'Uruguay', gnd: '4062186-8', historic: false },
  { code: 'USA', alpha2: 'US', name: 'Vereinigte Staaten', gnd: '4078704-7', historic: false },
  { code: 'UZB', alpha2: 'UZ', name: 'Usbekistan', gnd: '4062199-6', historic: false },
  { code: 'VAT', alpha2: 'VA', name: 'Vatikanstadt', gnd: '4062404-3', historic: false },
  { code: 'VCT', alpha2: 'VC', name: 'St. Vincent und die Grenadinen', gnd: '4051308-7', historic: false },
  { code: 'VEN', alpha2: 'VE', name: 'Venezuela', gnd: '4062512-6', historic: false },
  { code: 'VGB', alpha2: 'VG', name: 'Britische Jungferninseln', gnd: '4063590-9', historic: false },
  { code: 'VIR', alpha2: 'VI', name: 'Amerikanische Jungferninseln', gnd: '4108287-4', historic: false },
  { code: 'VNM', alpha2: 'VN', name: 'Vietnam', gnd: '4063514-4', historic: false },
  { code: 'VUT', alpha2: 'VU', name: 'Vanuatu', gnd: '4062334-8', historic: false },
  { code: 'WLF', alpha2: 'WF', name: 'Wallis und Futuna', gnd: '4210894-9', historic: false },
  { code: 'WSM', alpha2: 'WS', name: 'Samoa', gnd: '4079249-3', historic: false },
  { code: 'XKS', alpha2: 'XK', name: 'Kosovo', gnd: '4032571-4', historic: false },
  { code: 'YEM', alpha2: 'YE', name: 'Jemen', gnd: '4073009-8', historic: false },
  { code: 'YUG', alpha2: '', name: 'Jugoslawien', gnd: '4028966-7', historic: true },
  { code: 'ZAF', alpha2: 'ZA', name: 'Südafrika', gnd: '4078012-0', historic: false },
  { code: 'ZMB', alpha2: 'ZM', name: 'Sambia', gnd: '4076986-0', historic: false },
  { code: 'ZWE', alpha2: 'ZW', name: 'Simbabwe', gnd: '4049850-5', historic: false },
  { code: 'CSSR', alpha2: '', name: 'Tschechoslowakei', gnd: '4078435-6', historic: true },
  { code: 'DDE', alpha2: '', name: 'Deutsches Reich', gnd: '2008993-4', historic: true },
  { code: 'DE BIS 1945', alpha2: '', name: 'Deutsches Reich', gnd: '2008993-4', historic: true },
  { code: 'DEUTSCHES REICH', alpha2: '', name: 'Deutsches Reich', gnd: '2008993-4', historic: true },
]

/** Schreibweise -> Code eines Eintrags aus COUNTRY_ENTRIES. */
export const COUNTRY_ALIASES: Readonly<Record<string, string>> = {
  'A': 'AUT',
  'B': 'BEL',
  'BRD': 'DEU',
  'CH': 'CHE',
  'CS': 'CSK',
  'CSFR': 'CSK',
  'D': 'DEU',
  'DEUTSCHLAND': 'DEU',
  'DK': 'DNK',
  'E': 'ESP',
  'ENG': 'GBR',
  'F': 'FRA',
  'GB': 'GBR',
  'GER': 'DEU',
  'GROSSBRITANNIEN': 'GBR',
  'I': 'ITA',
  'JUGOSLAWIEN': 'YUG',
  'N': 'NOR',
  'NL': 'NLD',
  'S': 'SWE',
  'SOWJETUNION': 'SUN',
  'SU': 'SUN',
  'TSCHECHOSLOWAKEI': 'CSK',
  'UDSSR': 'SUN',
  'UK': 'GBR',
  'US': 'USA',
  'USA': 'USA',
  'VEREINIGTE STAATEN': 'USA',
  'WEST-DEUTSCHLAND': 'DEU',
  'WESTDEUTSCHLAND': 'DEU',
  'YU': 'YUG',
}
