/*
 * Sprachtabelle nach ISO 639-2 — Datenteil.
 *
 * Erzeugt aus der amtlichen Codeliste der Library of Congress
 * (ISO-639-2_utf-8.txt: bibliografischer Code | terminologischer Code |
 * ISO 639-1 | englische Bezeichnungen | franzoesische Bezeichnungen),
 * ergaenzt um die deutschen Bezeichnungen aus Wikidata (Eigenschaft P219).
 *
 * Zielformat des Konverters ist der bibliografische Code (639-2/B), so wie ihn
 * das AVefi-Schema erwartet: Deutsch ist "ger", nicht "deu".
 *
 * Die Datei liegt im Repo und wird zur Laufzeit nicht nachgeladen. Wer eine
 * eigene Schreibweise braucht, traegt sie in LANGUAGE_EXTRA (languages.ts) nach.
 */

export interface LanguageEntry {
  /** ISO 639-2/B, der Zielwert. */
  code: string
  /** ISO 639-2/T, falls abweichend, sonst leer. */
  term: string
  /** ISO 639-1, falls vorhanden, sonst leer. */
  alpha2: string
  /** Englische Bezeichnungen; die erste ist die gebraeuchliche. */
  en: readonly string[]
  /** Deutsche Bezeichnung, soweit bekannt, sonst leer. */
  de: string
}

export const LANGUAGE_ENTRIES: readonly LanguageEntry[] = [
  { code: 'aar', term: '', alpha2: 'aa', en: ['Afar'], de: 'Afar' },
  { code: 'abk', term: '', alpha2: 'ab', en: ['Abkhazian'], de: 'Abchasisch' },
  { code: 'ace', term: '', alpha2: '', en: ['Achinese'], de: 'Achinesisch' },
  { code: 'ach', term: '', alpha2: '', en: ['Acoli'], de: 'Acholi' },
  { code: 'ada', term: '', alpha2: '', en: ['Adangme'], de: 'Dangme' },
  { code: 'ady', term: '', alpha2: '', en: ['Adyghe', 'Adygei'], de: 'Adygeisch' },
  { code: 'afa', term: '', alpha2: '', en: ['Afro-Asiatic languages'], de: 'Afroasiatisch' },
  { code: 'afh', term: '', alpha2: '', en: ['Afrihili'], de: 'Afrihili' },
  { code: 'afr', term: '', alpha2: 'af', en: ['Afrikaans'], de: 'Afrikaans' },
  { code: 'ain', term: '', alpha2: '', en: ['Ainu'], de: 'Ainu' },
  { code: 'aka', term: '', alpha2: 'ak', en: ['Akan'], de: 'Akan' },
  { code: 'akk', term: '', alpha2: '', en: ['Akkadian'], de: 'Akkadisch' },
  { code: 'alb', term: 'sqi', alpha2: 'sq', en: ['Albanian'], de: 'Albanisch' },
  { code: 'ale', term: '', alpha2: '', en: ['Aleut'], de: 'Aleutisch' },
  { code: 'alg', term: '', alpha2: '', en: ['Algonquian languages'], de: 'Algonkin-Sprachen' },
  { code: 'alt', term: '', alpha2: '', en: ['Southern Altai'], de: 'Südaltaisch' },
  { code: 'amh', term: '', alpha2: 'am', en: ['Amharic'], de: 'Amharisch' },
  { code: 'ang', term: '', alpha2: '', en: ['English, Old (ca.450-1100)'], de: 'Altenglisch' },
  { code: 'anp', term: '', alpha2: '', en: ['Angika'], de: 'Angika' },
  { code: 'apa', term: '', alpha2: '', en: ['Apache languages'], de: 'Apache-Sprachen' },
  { code: 'ara', term: '', alpha2: 'ar', en: ['Arabic'], de: 'Arabisch' },
  { code: 'arc', term: '', alpha2: '', en: ['Official Aramaic (700-300 BCE)', 'Imperial Aramaic (700-300 BCE)'], de: 'Reichsaramäisch' },
  { code: 'arg', term: '', alpha2: 'an', en: ['Aragonese'], de: 'Aragonesisch' },
  { code: 'arm', term: 'hye', alpha2: 'hy', en: ['Armenian'], de: 'Armenisch' },
  { code: 'arn', term: '', alpha2: '', en: ['Mapudungun', 'Mapuche'], de: 'Mapudungun' },
  { code: 'arp', term: '', alpha2: '', en: ['Arapaho'], de: 'Arapaho' },
  { code: 'art', term: '', alpha2: '', en: ['Artificial languages'], de: 'konstruierte Sprache' },
  { code: 'arw', term: '', alpha2: '', en: ['Arawak'], de: 'Arawak' },
  { code: 'asm', term: '', alpha2: 'as', en: ['Assamese'], de: 'Assamesisch' },
  { code: 'ast', term: '', alpha2: '', en: ['Asturian', 'Bable', 'Leonese', 'Asturleonese'], de: 'Asturisch' },
  { code: 'ath', term: '', alpha2: '', en: ['Athapascan languages'], de: 'Athapaskisch' },
  { code: 'aus', term: '', alpha2: '', en: ['Australian languages'], de: 'australische Aboriginessprachen' },
  { code: 'ava', term: '', alpha2: 'av', en: ['Avaric'], de: 'Awarisch' },
  { code: 'ave', term: '', alpha2: 'ae', en: ['Avestan'], de: 'Avestisch' },
  { code: 'awa', term: '', alpha2: '', en: ['Awadhi'], de: 'Awadhi' },
  { code: 'aym', term: '', alpha2: 'ay', en: ['Aymara'], de: 'Aymara' },
  { code: 'aze', term: '', alpha2: 'az', en: ['Azerbaijani'], de: 'Aserbaidschanisch' },
  { code: 'bad', term: '', alpha2: '', en: ['Banda languages'], de: 'Banda-Sprachen' },
  { code: 'bai', term: '', alpha2: '', en: ['Bamileke languages'], de: 'Bamileke-Sprachen' },
  { code: 'bak', term: '', alpha2: 'ba', en: ['Bashkir'], de: 'Baschkirisch' },
  { code: 'bal', term: '', alpha2: '', en: ['Baluchi'], de: 'Belutschisch' },
  { code: 'bam', term: '', alpha2: 'bm', en: ['Bambara'], de: 'Bambara' },
  { code: 'ban', term: '', alpha2: '', en: ['Balinese'], de: 'Balinesisch' },
  { code: 'baq', term: 'eus', alpha2: 'eu', en: ['Basque'], de: 'Baskisch' },
  { code: 'bas', term: '', alpha2: '', en: ['Basa'], de: 'Bassa' },
  { code: 'bat', term: '', alpha2: '', en: ['Baltic languages'], de: 'Baltisch' },
  { code: 'bej', term: '', alpha2: '', en: ['Beja', 'Bedawiyet'], de: 'Bedscha' },
  { code: 'bel', term: '', alpha2: 'be', en: ['Belarusian'], de: 'Belarussisch' },
  { code: 'bem', term: '', alpha2: '', en: ['Bemba'], de: 'Bemba' },
  { code: 'ben', term: '', alpha2: 'bn', en: ['Bengali'], de: 'Bengalisch' },
  { code: 'ber', term: '', alpha2: '', en: ['Berber languages'], de: 'Berbersprachen' },
  { code: 'bho', term: '', alpha2: '', en: ['Bhojpuri'], de: 'Bhojpuri' },
  { code: 'bih', term: '', alpha2: '', en: ['Bihari languages'], de: 'Bihari' },
  { code: 'bik', term: '', alpha2: '', en: ['Bikol'], de: 'Bikolano' },
  { code: 'bin', term: '', alpha2: '', en: ['Bini', 'Edo'], de: 'Edo' },
  { code: 'bis', term: '', alpha2: 'bi', en: ['Bislama'], de: 'Bislama' },
  { code: 'bla', term: '', alpha2: '', en: ['Siksika'], de: 'Blackfoot' },
  { code: 'bnt', term: '', alpha2: '', en: ['Bantu languages'], de: 'Bantusprachen' },
  { code: 'bos', term: '', alpha2: 'bs', en: ['Bosnian'], de: 'Bosnisch' },
  { code: 'bra', term: '', alpha2: '', en: ['Braj'], de: 'Braj-Bhakha' },
  { code: 'bre', term: '', alpha2: 'br', en: ['Breton'], de: 'Bretonisch' },
  { code: 'btk', term: '', alpha2: '', en: ['Batak languages'], de: 'Bataksprachen' },
  { code: 'bua', term: '', alpha2: '', en: ['Buriat'], de: 'Burjatisch' },
  { code: 'bug', term: '', alpha2: '', en: ['Buginese'], de: 'Buginesisch' },
  { code: 'bul', term: '', alpha2: 'bg', en: ['Bulgarian'], de: 'Bulgarisch' },
  { code: 'bur', term: 'mya', alpha2: 'my', en: ['Burmese'], de: 'Birmanisch' },
  { code: 'byn', term: '', alpha2: '', en: ['Blin', 'Bilin'], de: 'Blin' },
  { code: 'cad', term: '', alpha2: '', en: ['Caddo'], de: '' },
  { code: 'cai', term: '', alpha2: '', en: ['Central American Indian languages'], de: '' },
  { code: 'car', term: '', alpha2: '', en: ['Galibi Carib'], de: '' },
  { code: 'cat', term: '', alpha2: 'ca', en: ['Catalan', 'Valencian'], de: 'Katalanisch' },
  { code: 'cau', term: '', alpha2: '', en: ['Caucasian languages'], de: 'Kaukasisch' },
  { code: 'ceb', term: '', alpha2: '', en: ['Cebuano'], de: 'Cebuano' },
  { code: 'cel', term: '', alpha2: '', en: ['Celtic languages'], de: 'Keltisch' },
  { code: 'cha', term: '', alpha2: 'ch', en: ['Chamorro'], de: 'Chamorro' },
  { code: 'chb', term: '', alpha2: '', en: ['Chibcha'], de: 'Chibcha' },
  { code: 'che', term: '', alpha2: 'ce', en: ['Chechen'], de: 'Tschetschenisch' },
  { code: 'chg', term: '', alpha2: '', en: ['Chagatai'], de: 'Tschagataisch' },
  { code: 'chi', term: 'zho', alpha2: 'zh', en: ['Chinese'], de: 'Chinesisch' },
  { code: 'chk', term: '', alpha2: '', en: ['Chuukese'], de: 'Chuukesisch' },
  { code: 'chm', term: '', alpha2: '', en: ['Mari'], de: 'Mari' },
  { code: 'chn', term: '', alpha2: '', en: ['Chinook jargon'], de: 'Chinook Wawa' },
  { code: 'cho', term: '', alpha2: '', en: ['Choctaw'], de: 'Choctaw' },
  { code: 'chp', term: '', alpha2: '', en: ['Chipewyan', 'Dene Suline'], de: 'Chipewyan' },
  { code: 'chr', term: '', alpha2: '', en: ['Cherokee'], de: 'Cherokee' },
  { code: 'chu', term: '', alpha2: 'cu', en: ['Church Slavic', 'Old Slavonic', 'Church Slavonic', 'Old Bulgarian', 'Old Church Slavonic'], de: 'Kirchenslawisch' },
  { code: 'chv', term: '', alpha2: 'cv', en: ['Chuvash'], de: 'Tschuwaschisch' },
  { code: 'chy', term: '', alpha2: '', en: ['Cheyenne'], de: 'Cheyenne' },
  { code: 'cmc', term: '', alpha2: '', en: ['Chamic languages'], de: 'Chamisch' },
  { code: 'cnr', term: '', alpha2: '', en: ['Montenegrin'], de: 'Montenegrinisch' },
  { code: 'cop', term: '', alpha2: '', en: ['Coptic'], de: 'Koptisch' },
  { code: 'cor', term: '', alpha2: 'kw', en: ['Cornish'], de: 'Kornisch' },
  { code: 'cos', term: '', alpha2: 'co', en: ['Corsican'], de: 'Korsisch' },
  { code: 'cpe', term: '', alpha2: '', en: ['Creoles and pidgins, English based'], de: 'Kreolisch-Englisch' },
  { code: 'cpf', term: '', alpha2: '', en: ['Creoles and pidgins, French-based'], de: 'französisch-basierte Kreolsprachen' },
  { code: 'cpp', term: '', alpha2: '', en: ['Creoles and pidgins, Portuguese-based'], de: 'portugiesisch-basierte Kreolsprachen' },
  { code: 'cre', term: '', alpha2: 'cr', en: ['Cree'], de: 'Cree' },
  { code: 'crh', term: '', alpha2: '', en: ['Crimean Tatar', 'Crimean Turkish'], de: 'Krimtatarisch' },
  { code: 'crp', term: '', alpha2: '', en: ['Creoles and pidgins'], de: 'Pidgin- oder Kreolsprache' },
  { code: 'csb', term: '', alpha2: '', en: ['Kashubian'], de: 'Kaschubisch' },
  { code: 'cus', term: '', alpha2: '', en: ['Cushitic languages'], de: 'Kuschitisch' },
  { code: 'cze', term: 'ces', alpha2: 'cs', en: ['Czech'], de: 'Tschechisch' },
  { code: 'dak', term: '', alpha2: '', en: ['Dakota'], de: 'Dakota' },
  { code: 'dan', term: '', alpha2: 'da', en: ['Danish'], de: 'Dänisch' },
  { code: 'dar', term: '', alpha2: '', en: ['Dargwa'], de: 'Darginisch' },
  { code: 'day', term: '', alpha2: '', en: ['Land Dayak languages'], de: '' },
  { code: 'del', term: '', alpha2: '', en: ['Delaware'], de: 'Delawarisch' },
  { code: 'den', term: '', alpha2: '', en: ['Slave (Athapascan)'], de: 'Slavey' },
  { code: 'dgr', term: '', alpha2: '', en: ['Tlicho', 'Dogrib'], de: 'Dogrib' },
  { code: 'din', term: '', alpha2: '', en: ['Dinka'], de: 'Dinka' },
  { code: 'div', term: '', alpha2: 'dv', en: ['Divehi', 'Dhivehi', 'Maldivian'], de: 'Dhivehi' },
  { code: 'doi', term: '', alpha2: '', en: ['Dogri'], de: 'Dogri–Kangri-Sprachen' },
  { code: 'dra', term: '', alpha2: '', en: ['Dravidian languages'], de: 'Dravidisch' },
  { code: 'dsb', term: '', alpha2: '', en: ['Lower Sorbian'], de: 'Niedersorbisch' },
  { code: 'dua', term: '', alpha2: '', en: ['Duala'], de: 'Duala' },
  { code: 'dum', term: '', alpha2: '', en: ['Dutch, Middle (ca.1050-1350)'], de: 'Mittelniederländisch' },
  { code: 'dut', term: 'nld', alpha2: 'nl', en: ['Dutch', 'Flemish'], de: 'Niederländisch' },
  { code: 'dyu', term: '', alpha2: '', en: ['Dyula'], de: 'Dioula' },
  { code: 'dzo', term: '', alpha2: 'dz', en: ['Dzongkha'], de: 'Dzongkha' },
  { code: 'efi', term: '', alpha2: '', en: ['Efik'], de: 'Efik' },
  { code: 'egy', term: '', alpha2: '', en: ['Egyptian (Ancient)'], de: 'Ägyptisch' },
  { code: 'eka', term: '', alpha2: '', en: ['Ekajuk'], de: 'Ekajuk' },
  { code: 'elx', term: '', alpha2: '', en: ['Elamite'], de: 'Elamisch' },
  { code: 'eng', term: '', alpha2: 'en', en: ['English'], de: 'Englisch' },
  { code: 'enm', term: '', alpha2: '', en: ['English, Middle (1100-1500)'], de: 'Mittelenglisch' },
  { code: 'epo', term: '', alpha2: 'eo', en: ['Esperanto'], de: 'Esperanto' },
  { code: 'est', term: '', alpha2: 'et', en: ['Estonian'], de: 'Estnisch' },
  { code: 'ewe', term: '', alpha2: 'ee', en: ['Ewe'], de: 'Ewe' },
  { code: 'ewo', term: '', alpha2: '', en: ['Ewondo'], de: 'Ewondo' },
  { code: 'fan', term: '', alpha2: '', en: ['Fang'], de: 'Fang' },
  { code: 'fao', term: '', alpha2: 'fo', en: ['Faroese'], de: 'Färöisch' },
  { code: 'fat', term: '', alpha2: '', en: ['Fanti'], de: 'Fante' },
  { code: 'fij', term: '', alpha2: 'fj', en: ['Fijian'], de: 'Fidschi' },
  { code: 'fil', term: '', alpha2: '', en: ['Filipino', 'Pilipino'], de: 'Filipino' },
  { code: 'fin', term: '', alpha2: 'fi', en: ['Finnish'], de: 'Finnisch' },
  { code: 'fiu', term: '', alpha2: '', en: ['Finno-Ugrian languages'], de: 'Finno-Ugrisch' },
  { code: 'fon', term: '', alpha2: '', en: ['Fon'], de: 'Fon' },
  { code: 'fre', term: 'fra', alpha2: 'fr', en: ['French'], de: 'Französisch' },
  { code: 'frm', term: '', alpha2: '', en: ['French, Middle (ca.1400-1600)'], de: 'Mittelfranzösisch' },
  { code: 'fro', term: '', alpha2: '', en: ['French, Old (842-ca.1400)'], de: 'Altfranzösisch' },
  { code: 'frr', term: '', alpha2: '', en: ['Northern Frisian'], de: 'nordfriesische Sprache' },
  { code: 'frs', term: '', alpha2: '', en: ['Eastern Frisian'], de: 'Ostfriesisches Niederdeutsch' },
  { code: 'fry', term: '', alpha2: 'fy', en: ['Western Frisian'], de: 'Westfriesisch' },
  { code: 'ful', term: '', alpha2: 'ff', en: ['Fulah'], de: 'Fulfulde' },
  { code: 'fur', term: '', alpha2: '', en: ['Friulian'], de: 'Furlanisch' },
  { code: 'gaa', term: '', alpha2: '', en: ['Ga'], de: 'Ga' },
  { code: 'gay', term: '', alpha2: '', en: ['Gayo'], de: 'Gayo' },
  { code: 'gba', term: '', alpha2: '', en: ['Gbaya'], de: 'Gbaya-Sprachen' },
  { code: 'gem', term: '', alpha2: '', en: ['Germanic languages'], de: 'Germanisch' },
  { code: 'geo', term: 'kat', alpha2: 'ka', en: ['Georgian'], de: 'Georgisch' },
  { code: 'ger', term: 'deu', alpha2: 'de', en: ['German'], de: 'Deutsch' },
  { code: 'gez', term: '', alpha2: '', en: ['Geez'], de: 'Ge’ez' },
  { code: 'gil', term: '', alpha2: '', en: ['Gilbertese'], de: 'Kiribatisch' },
  { code: 'gla', term: '', alpha2: 'gd', en: ['Gaelic', 'Scottish Gaelic'], de: 'Schottisch-Gälisch' },
  { code: 'gle', term: '', alpha2: 'ga', en: ['Irish'], de: 'Irisch' },
  { code: 'glg', term: '', alpha2: 'gl', en: ['Galician'], de: 'Galicisch' },
  { code: 'glv', term: '', alpha2: 'gv', en: ['Manx'], de: 'Manx' },
  { code: 'gmh', term: '', alpha2: '', en: ['German, Middle High (ca.1050-1500)'], de: 'Mittelhochdeutsch' },
  { code: 'goh', term: '', alpha2: '', en: ['German, Old High (ca.750-1050)'], de: 'Althochdeutsch' },
  { code: 'gon', term: '', alpha2: '', en: ['Gondi'], de: 'Gondi' },
  { code: 'gor', term: '', alpha2: '', en: ['Gorontalo'], de: 'Gorontalo' },
  { code: 'got', term: '', alpha2: '', en: ['Gothic'], de: 'Gotisch' },
  { code: 'grb', term: '', alpha2: '', en: ['Grebo'], de: 'Grebo' },
  { code: 'grc', term: '', alpha2: '', en: ['Greek, Ancient (to 1453)'], de: 'Altgriechisch' },
  { code: 'gre', term: 'ell', alpha2: 'el', en: ['Modern Greek (1453-)'], de: 'Neugriechisch' },
  { code: 'grn', term: '', alpha2: 'gn', en: ['Guarani'], de: 'Guaraní' },
  { code: 'gsw', term: '', alpha2: '', en: ['Swiss German', 'Alemannic', 'Alsatian'], de: 'Alemannisch' },
  { code: 'guj', term: '', alpha2: 'gu', en: ['Gujarati'], de: 'Gujarati' },
  { code: 'gwi', term: '', alpha2: '', en: ['Gwich\'in'], de: 'Gwichʼin' },
  { code: 'hai', term: '', alpha2: '', en: ['Haida'], de: 'Haida' },
  { code: 'hat', term: '', alpha2: 'ht', en: ['Haitian', 'Haitian Creole'], de: 'Haitianisch-Kreolisch' },
  { code: 'hau', term: '', alpha2: 'ha', en: ['Hausa'], de: 'Hausa' },
  { code: 'haw', term: '', alpha2: '', en: ['Hawaiian'], de: 'Hawaiisch' },
  { code: 'heb', term: '', alpha2: 'he', en: ['Hebrew'], de: 'Hebräisch' },
  { code: 'her', term: '', alpha2: 'hz', en: ['Herero'], de: 'Otjiherero' },
  { code: 'hil', term: '', alpha2: '', en: ['Hiligaynon'], de: 'Hiligaynon' },
  { code: 'him', term: '', alpha2: '', en: ['Himachali languages', 'Western Pahari languages'], de: 'West-Pahari-Sprachen' },
  { code: 'hin', term: '', alpha2: 'hi', en: ['Hindi'], de: 'Hindi' },
  { code: 'hit', term: '', alpha2: '', en: ['Hittite'], de: 'Hethitisch' },
  { code: 'hmn', term: '', alpha2: '', en: ['Hmong', 'Mong'], de: '' },
  { code: 'hmo', term: '', alpha2: 'ho', en: ['Hiri Motu'], de: 'Hiri Motu' },
  { code: 'hrv', term: '', alpha2: 'hr', en: ['Croatian'], de: 'Kroatisch' },
  { code: 'hsb', term: '', alpha2: '', en: ['Upper Sorbian'], de: 'Obersorbisch' },
  { code: 'hun', term: '', alpha2: 'hu', en: ['Hungarian'], de: 'Ungarisch' },
  { code: 'hup', term: '', alpha2: '', en: ['Hupa'], de: 'Hupa' },
  { code: 'iba', term: '', alpha2: '', en: ['Iban'], de: 'Iban' },
  { code: 'ibo', term: '', alpha2: 'ig', en: ['Igbo'], de: 'Igbo' },
  { code: 'ice', term: 'isl', alpha2: 'is', en: ['Icelandic'], de: 'Isländisch' },
  { code: 'ido', term: '', alpha2: 'io', en: ['Ido'], de: 'Ido' },
  { code: 'iii', term: '', alpha2: 'ii', en: ['Sichuan Yi', 'Nuosu'], de: 'Nuosu-Sprache' },
  { code: 'ijo', term: '', alpha2: '', en: ['Ijo languages'], de: 'Ijo-Sprachen' },
  { code: 'iku', term: '', alpha2: 'iu', en: ['Inuktitut'], de: 'Inuktitut' },
  { code: 'ile', term: '', alpha2: 'ie', en: ['Interlingue', 'Occidental'], de: 'Interlingue' },
  { code: 'ilo', term: '', alpha2: '', en: ['Iloko'], de: 'Ilokano' },
  { code: 'ina', term: '', alpha2: 'ia', en: ['Interlingua (International Auxiliary Language Association)'], de: 'Interlingua' },
  { code: 'inc', term: '', alpha2: '', en: ['Indic languages'], de: 'Indoarisch' },
  { code: 'ind', term: '', alpha2: 'id', en: ['Indonesian'], de: 'Indonesisch' },
  { code: 'ine', term: '', alpha2: '', en: ['Indo-European languages'], de: 'indogermanische Sprachen' },
  { code: 'inh', term: '', alpha2: '', en: ['Ingush'], de: 'Inguschisch' },
  { code: 'ipk', term: '', alpha2: 'ik', en: ['Inupiaq'], de: 'Inupiaq' },
  { code: 'ira', term: '', alpha2: '', en: ['Iranian languages'], de: 'Iranisch' },
  { code: 'iro', term: '', alpha2: '', en: ['Iroquoian languages'], de: 'Irokesisch' },
  { code: 'ita', term: '', alpha2: 'it', en: ['Italian'], de: 'Italienisch' },
  { code: 'jav', term: '', alpha2: 'jv', en: ['Javanese'], de: 'Javanisch' },
  { code: 'jbo', term: '', alpha2: '', en: ['Lojban'], de: 'Lojban' },
  { code: 'jpn', term: '', alpha2: 'ja', en: ['Japanese'], de: 'Japanisch' },
  { code: 'jpr', term: '', alpha2: '', en: ['Judeo-Persian'], de: 'Judäo-Persisch' },
  { code: 'jrb', term: '', alpha2: '', en: ['Judeo-Arabic'], de: 'Judäo-Arabisch' },
  { code: 'kaa', term: '', alpha2: '', en: ['Kara-Kalpak'], de: 'Karakalpakisch' },
  { code: 'kab', term: '', alpha2: '', en: ['Kabyle'], de: 'Kabylisch' },
  { code: 'kac', term: '', alpha2: '', en: ['Kachin', 'Jingpho'], de: 'Jingpho' },
  { code: 'kal', term: '', alpha2: 'kl', en: ['Kalaallisut', 'Greenlandic'], de: 'Grönländisch' },
  { code: 'kam', term: '', alpha2: '', en: ['Kamba'], de: 'Kikamba' },
  { code: 'kan', term: '', alpha2: 'kn', en: ['Kannada'], de: 'Kannada' },
  { code: 'kar', term: '', alpha2: '', en: ['Karen languages'], de: 'Karenisch' },
  { code: 'kas', term: '', alpha2: 'ks', en: ['Kashmiri'], de: 'Kashmiri' },
  { code: 'kau', term: '', alpha2: 'kr', en: ['Kanuri'], de: 'Kanuri' },
  { code: 'kaw', term: '', alpha2: '', en: ['Kawi'], de: '' },
  { code: 'kaz', term: '', alpha2: 'kk', en: ['Kazakh'], de: 'Kasachisch' },
  { code: 'kbd', term: '', alpha2: '', en: ['Kabardian'], de: 'Kabardinisch' },
  { code: 'kha', term: '', alpha2: '', en: ['Khasi'], de: 'Khasi' },
  { code: 'khi', term: '', alpha2: '', en: ['Khoisan languages'], de: 'Khoisansprachen' },
  { code: 'khm', term: '', alpha2: 'km', en: ['Central Khmer'], de: 'Khmer' },
  { code: 'kho', term: '', alpha2: '', en: ['Khotanese', 'Sakan'], de: 'Sakisch' },
  { code: 'kik', term: '', alpha2: 'ki', en: ['Kikuyu', 'Gikuyu'], de: 'Kikuyu' },
  { code: 'kin', term: '', alpha2: 'rw', en: ['Kinyarwanda'], de: 'Kinyarwanda' },
  { code: 'kir', term: '', alpha2: 'ky', en: ['Kirghiz', 'Kyrgyz'], de: 'Kirgisisch' },
  { code: 'kmb', term: '', alpha2: '', en: ['Kimbundu'], de: 'Kimbundu' },
  { code: 'kok', term: '', alpha2: '', en: ['Konkani'], de: 'Konkani' },
  { code: 'kom', term: '', alpha2: 'kv', en: ['Komi'], de: 'Komi' },
  { code: 'kon', term: '', alpha2: 'kg', en: ['Kongo'], de: 'Kikongo' },
  { code: 'kor', term: '', alpha2: 'ko', en: ['Korean'], de: 'Koreanisch' },
  { code: 'kos', term: '', alpha2: '', en: ['Kosraean'], de: 'Kosraeanisch' },
  { code: 'kpe', term: '', alpha2: '', en: ['Kpelle'], de: 'Kpelle' },
  { code: 'krc', term: '', alpha2: '', en: ['Karachay-Balkar'], de: 'Karatschai-Balkarisch' },
  { code: 'krl', term: '', alpha2: '', en: ['Karelian'], de: 'Karelisch' },
  { code: 'kro', term: '', alpha2: '', en: ['Kru languages'], de: 'Kru-Sprachen' },
  { code: 'kru', term: '', alpha2: '', en: ['Kurukh'], de: 'Kurukh' },
  { code: 'kua', term: '', alpha2: 'kj', en: ['Kuanyama', 'Kwanyama'], de: 'Kwanyama' },
  { code: 'kum', term: '', alpha2: '', en: ['Kumyk'], de: 'Kumykisch' },
  { code: 'kur', term: '', alpha2: 'ku', en: ['Kurdish'], de: 'Kurdisch' },
  { code: 'kut', term: '', alpha2: '', en: ['Kutenai'], de: 'Kutanaha' },
  { code: 'lad', term: '', alpha2: '', en: ['Ladino'], de: 'Sephardisch' },
  { code: 'lah', term: '', alpha2: '', en: ['Lahnda'], de: '' },
  { code: 'lam', term: '', alpha2: '', en: ['Lamba'], de: 'Lamba' },
  { code: 'lao', term: '', alpha2: 'lo', en: ['Lao'], de: 'Laotisch' },
  { code: 'lat', term: '', alpha2: 'la', en: ['Latin'], de: 'Latein' },
  { code: 'lav', term: '', alpha2: 'lv', en: ['Latvian'], de: 'Lettisch' },
  { code: 'lez', term: '', alpha2: '', en: ['Lezghian'], de: 'Lesgisch' },
  { code: 'lim', term: '', alpha2: 'li', en: ['Limburgan', 'Limburger', 'Limburgish'], de: 'limburgische Sprache' },
  { code: 'lin', term: '', alpha2: 'ln', en: ['Lingala'], de: 'Lingala' },
  { code: 'lit', term: '', alpha2: 'lt', en: ['Lithuanian'], de: 'Litauisch' },
  { code: 'lol', term: '', alpha2: '', en: ['Mongo'], de: 'Lomongo' },
  { code: 'loz', term: '', alpha2: '', en: ['Lozi'], de: 'Lozi' },
  { code: 'ltz', term: '', alpha2: 'lb', en: ['Luxembourgish', 'Letzeburgesch'], de: 'Luxemburgisch' },
  { code: 'lua', term: '', alpha2: '', en: ['Luba-Lulua'], de: 'Tschiluba' },
  { code: 'lub', term: '', alpha2: 'lu', en: ['Luba-Katanga'], de: 'Kiluba' },
  { code: 'lug', term: '', alpha2: 'lg', en: ['Ganda'], de: '' },
  { code: 'lui', term: '', alpha2: '', en: ['Luiseno'], de: '' },
  { code: 'lun', term: '', alpha2: '', en: ['Lunda'], de: 'Chilunda' },
  { code: 'luo', term: '', alpha2: '', en: ['Luo (Kenya and Tanzania)'], de: 'Luo' },
  { code: 'lus', term: '', alpha2: '', en: ['Lushai'], de: 'Mizo' },
  { code: 'mac', term: 'mkd', alpha2: 'mk', en: ['Macedonian'], de: 'Mazedonisch' },
  { code: 'mad', term: '', alpha2: '', en: ['Madurese'], de: 'Madura' },
  { code: 'mag', term: '', alpha2: '', en: ['Magahi'], de: 'Magahi' },
  { code: 'mah', term: '', alpha2: 'mh', en: ['Marshallese'], de: 'Marshallesisch' },
  { code: 'mai', term: '', alpha2: '', en: ['Maithili'], de: 'Maithili' },
  { code: 'mak', term: '', alpha2: '', en: ['Makasar'], de: 'Makassar-Sprache' },
  { code: 'mal', term: '', alpha2: 'ml', en: ['Malayalam'], de: 'Malayalam' },
  { code: 'man', term: '', alpha2: '', en: ['Mandingo'], de: 'Manding-Sprachen' },
  { code: 'mao', term: 'mri', alpha2: 'mi', en: ['Maori'], de: 'Māori' },
  { code: 'map', term: '', alpha2: '', en: ['Austronesian languages'], de: 'Austronesisch' },
  { code: 'mar', term: '', alpha2: 'mr', en: ['Marathi'], de: 'Marathi' },
  { code: 'mas', term: '', alpha2: '', en: ['Masai'], de: 'Maa' },
  { code: 'may', term: 'msa', alpha2: 'ms', en: ['Malay'], de: 'Malaiisch' },
  { code: 'mdf', term: '', alpha2: '', en: ['Moksha'], de: 'Mokschanisch' },
  { code: 'mdr', term: '', alpha2: '', en: ['Mandar'], de: 'Mandar' },
  { code: 'men', term: '', alpha2: '', en: ['Mende'], de: 'Mende' },
  { code: 'mga', term: '', alpha2: '', en: ['Irish, Middle (900-1200)'], de: 'Mittelirisch' },
  { code: 'mic', term: '', alpha2: '', en: ['Mi\'kmaq', 'Micmac'], de: 'Micmac-Sprache' },
  { code: 'min', term: '', alpha2: '', en: ['Minangkabau'], de: 'Minangkabauisch' },
  { code: 'mis', term: '', alpha2: '', en: ['Uncoded languages'], de: 'Sprache ohne Sprachcode' },
  { code: 'mkh', term: '', alpha2: '', en: ['Mon-Khmer languages'], de: 'Mon-Khmer-Sprachen' },
  { code: 'mlg', term: '', alpha2: 'mg', en: ['Malagasy'], de: 'Malagasy' },
  { code: 'mlt', term: '', alpha2: 'mt', en: ['Maltese'], de: 'Maltesisch' },
  { code: 'mnc', term: '', alpha2: '', en: ['Manchu'], de: 'Mandschurisch' },
  { code: 'mni', term: '', alpha2: '', en: ['Manipuri'], de: 'Meitei' },
  { code: 'mno', term: '', alpha2: '', en: ['Manobo languages'], de: 'Manobo-Sprachen' },
  { code: 'moh', term: '', alpha2: '', en: ['Mohawk'], de: 'Mohawk' },
  { code: 'mon', term: '', alpha2: 'mn', en: ['Mongolian'], de: 'Mongolisch' },
  { code: 'mos', term: '', alpha2: '', en: ['Mossi'], de: 'Mòoré' },
  { code: 'mul', term: '', alpha2: '', en: ['Multiple languages'], de: 'mehrere Sprachen' },
  { code: 'mun', term: '', alpha2: '', en: ['Munda languages'], de: 'Munda-Sprachen' },
  { code: 'mus', term: '', alpha2: '', en: ['Creek'], de: 'Maskoki' },
  { code: 'mwl', term: '', alpha2: '', en: ['Mirandese'], de: 'Mirandés' },
  { code: 'mwr', term: '', alpha2: '', en: ['Marwari'], de: 'Marwari' },
  { code: 'myn', term: '', alpha2: '', en: ['Mayan languages'], de: 'Maya-Sprachen' },
  { code: 'myv', term: '', alpha2: '', en: ['Erzya'], de: 'Ersjanisch' },
  { code: 'nah', term: '', alpha2: '', en: ['Nahuatl languages'], de: 'Nahuatl' },
  { code: 'nai', term: '', alpha2: '', en: ['North American Indian languages'], de: 'indigene nordamerikanische Sprache' },
  { code: 'nap', term: '', alpha2: '', en: ['Neapolitan'], de: 'Neapolitanisch' },
  { code: 'nau', term: '', alpha2: 'na', en: ['Nauru'], de: 'Nauruisch' },
  { code: 'nav', term: '', alpha2: 'nv', en: ['Navajo', 'Navaho'], de: 'Navajo' },
  { code: 'nbl', term: '', alpha2: 'nr', en: ['South Ndebele'], de: 'Süd-Ndebele' },
  { code: 'nde', term: '', alpha2: 'nd', en: ['North Ndebele'], de: 'Nord-Ndebele' },
  { code: 'ndo', term: '', alpha2: 'ng', en: ['Ndonga'], de: 'Ndonga' },
  { code: 'nds', term: '', alpha2: '', en: ['Low German', 'Low Saxon', 'German, Low', 'Saxon, Low'], de: 'Niederdeutsch' },
  { code: 'nep', term: '', alpha2: 'ne', en: ['Nepali'], de: 'Nepali' },
  { code: 'new', term: '', alpha2: '', en: ['Nepal Bhasa', 'Newar', 'Newari'], de: 'Newari' },
  { code: 'nia', term: '', alpha2: '', en: ['Nias'], de: 'Nias' },
  { code: 'nic', term: '', alpha2: '', en: ['Niger-Kordofanian languages'], de: 'Niger-Kongo-Sprachen' },
  { code: 'niu', term: '', alpha2: '', en: ['Niuean'], de: 'Niueanisch' },
  { code: 'nno', term: '', alpha2: 'nn', en: ['Norwegian Nynorsk'], de: 'Nynorsk' },
  { code: 'nob', term: '', alpha2: 'nb', en: ['Norwegian Bokmål'], de: 'Bokmål' },
  { code: 'nog', term: '', alpha2: '', en: ['Nogai'], de: 'Nogaisch' },
  { code: 'non', term: '', alpha2: '', en: ['Norse, Old'], de: 'Altnordisch' },
  { code: 'nor', term: '', alpha2: 'no', en: ['Norwegian'], de: 'Norwegisch' },
  { code: 'nqo', term: '', alpha2: '', en: ['N\'Ko'], de: '' },
  { code: 'nso', term: '', alpha2: '', en: ['Pedi', 'Sepedi', 'Northern Sotho'], de: 'Nord-Sotho' },
  { code: 'nub', term: '', alpha2: '', en: ['Nubian languages'], de: 'Nubisch' },
  { code: 'nwc', term: '', alpha2: '', en: ['Classical Newari', 'Old Newari', 'Classical Nepal Bhasa'], de: 'klassisches Newari' },
  { code: 'nya', term: '', alpha2: 'ny', en: ['Chichewa', 'Chewa', 'Nyanja'], de: 'Chichewa' },
  { code: 'nym', term: '', alpha2: '', en: ['Nyamwezi'], de: '' },
  { code: 'nyn', term: '', alpha2: '', en: ['Nyankole'], de: 'Runyankole' },
  { code: 'nyo', term: '', alpha2: '', en: ['Nyoro'], de: '' },
  { code: 'nzi', term: '', alpha2: '', en: ['Nzima'], de: 'Nzema' },
  { code: 'oci', term: '', alpha2: 'oc', en: ['Occitan (post 1500)'], de: 'Okzitanisch' },
  { code: 'oji', term: '', alpha2: 'oj', en: ['Ojibwa'], de: 'Ojibwe' },
  { code: 'ori', term: '', alpha2: 'or', en: ['Oriya'], de: 'Oriya' },
  { code: 'orm', term: '', alpha2: 'om', en: ['Oromo'], de: 'Oromo' },
  { code: 'osa', term: '', alpha2: '', en: ['Osage'], de: '' },
  { code: 'oss', term: '', alpha2: 'os', en: ['Ossetian', 'Ossetic'], de: '' },
  { code: 'ota', term: '', alpha2: '', en: ['Turkish, Ottoman (1500-1928)'], de: 'Osmanisch' },
  { code: 'oto', term: '', alpha2: '', en: ['Otomian languages'], de: '' },
  { code: 'paa', term: '', alpha2: '', en: ['Papuan languages'], de: 'Papua-Sprachen' },
  { code: 'pag', term: '', alpha2: '', en: ['Pangasinan'], de: 'Pangasinensisch' },
  { code: 'pal', term: '', alpha2: '', en: ['Pahlavi'], de: 'Mittelpersisch' },
  { code: 'pam', term: '', alpha2: '', en: ['Pampanga', 'Kapampangan'], de: 'Kapampangan' },
  { code: 'pan', term: '', alpha2: 'pa', en: ['Panjabi', 'Punjabi'], de: 'Panjabi' },
  { code: 'pap', term: '', alpha2: '', en: ['Papiamento'], de: 'Papiamentu' },
  { code: 'pau', term: '', alpha2: '', en: ['Palauan'], de: 'Palauisch' },
  { code: 'peo', term: '', alpha2: '', en: ['Persian, Old (ca.600-400 B.C.)'], de: 'Altpersisch' },
  { code: 'per', term: 'fas', alpha2: 'fa', en: ['Persian'], de: 'Persisch' },
  { code: 'phi', term: '', alpha2: '', en: ['Philippine languages'], de: 'Philippinisch' },
  { code: 'phn', term: '', alpha2: '', en: ['Phoenician'], de: 'Phönizisch' },
  { code: 'pli', term: '', alpha2: 'pi', en: ['Pali'], de: 'Pali' },
  { code: 'pol', term: '', alpha2: 'pl', en: ['Polish'], de: 'Polnisch' },
  { code: 'pon', term: '', alpha2: '', en: ['Pohnpeian'], de: 'Pohnpeanisch' },
  { code: 'por', term: '', alpha2: 'pt', en: ['Portuguese'], de: 'Portugiesisch' },
  { code: 'pra', term: '', alpha2: '', en: ['Prakrit languages'], de: 'Prakrit' },
  { code: 'pro', term: '', alpha2: '', en: ['Provençal, Old (to 1500)', 'Occitan, Old (to 1500)'], de: 'Altokzitanisch' },
  { code: 'pus', term: '', alpha2: 'ps', en: ['Pushto', 'Pashto'], de: 'Paschtu' },
  { code: 'qaa-qtz', term: '', alpha2: '', en: ['Reserved for local use'], de: '' },
  { code: 'que', term: '', alpha2: 'qu', en: ['Quechua'], de: 'Quechua' },
  { code: 'raj', term: '', alpha2: '', en: ['Rajasthani'], de: 'Rajasthani' },
  { code: 'rap', term: '', alpha2: '', en: ['Rapanui'], de: 'Rapanui' },
  { code: 'rar', term: '', alpha2: '', en: ['Rarotongan', 'Cook Islands Maori'], de: 'Rarotonganisch' },
  { code: 'roa', term: '', alpha2: '', en: ['Romance languages'], de: 'Romanisch' },
  { code: 'roh', term: '', alpha2: 'rm', en: ['Romansh'], de: 'Bündnerromanisch' },
  { code: 'rom', term: '', alpha2: '', en: ['Romany'], de: 'Romani' },
  { code: 'rum', term: 'ron', alpha2: 'ro', en: ['Romanian', 'Moldavian', 'Moldovan'], de: 'Rumänisch' },
  { code: 'run', term: '', alpha2: 'rn', en: ['Rundi'], de: 'Kirundi' },
  { code: 'rup', term: '', alpha2: '', en: ['Aromanian', 'Arumanian', 'Macedo-Romanian'], de: 'Aromunische Sprache' },
  { code: 'rus', term: '', alpha2: 'ru', en: ['Russian'], de: 'Russisch' },
  { code: 'sad', term: '', alpha2: '', en: ['Sandawe'], de: 'Sandawe' },
  { code: 'sag', term: '', alpha2: 'sg', en: ['Sango'], de: 'Sango' },
  { code: 'sah', term: '', alpha2: '', en: ['Yakut'], de: 'Jakutisch' },
  { code: 'sai', term: '', alpha2: '', en: ['South American Indian languages'], de: 'indigene südamerikanische Sprache' },
  { code: 'sal', term: '', alpha2: '', en: ['Salishan languages'], de: 'Salish-Sprachen' },
  { code: 'sam', term: '', alpha2: '', en: ['Samaritan Aramaic'], de: '' },
  { code: 'san', term: '', alpha2: 'sa', en: ['Sanskrit'], de: 'Sanskrit' },
  { code: 'sas', term: '', alpha2: '', en: ['Sasak'], de: 'Sasak' },
  { code: 'sat', term: '', alpha2: '', en: ['Santali'], de: 'Santali' },
  { code: 'scn', term: '', alpha2: '', en: ['Sicilian'], de: 'Sizilianisch' },
  { code: 'sco', term: '', alpha2: '', en: ['Scots'], de: 'Scots' },
  { code: 'sel', term: '', alpha2: '', en: ['Selkup'], de: 'Selkupisch' },
  { code: 'sem', term: '', alpha2: '', en: ['Semitic languages'], de: 'Semitisch' },
  { code: 'sga', term: '', alpha2: '', en: ['Irish, Old (to 900)'], de: 'Altirisch' },
  { code: 'sgn', term: '', alpha2: '', en: ['Sign Languages'], de: 'Gebärdensprache' },
  { code: 'shn', term: '', alpha2: '', en: ['Shan'], de: 'Shan' },
  { code: 'sid', term: '', alpha2: '', en: ['Sidamo'], de: 'Sidama' },
  { code: 'sin', term: '', alpha2: 'si', en: ['Sinhala', 'Sinhalese'], de: 'Singhalesisch' },
  { code: 'sio', term: '', alpha2: '', en: ['Siouan languages'], de: 'Sioux-Sprachen' },
  { code: 'sit', term: '', alpha2: '', en: ['Sino-Tibetan languages'], de: 'Sino-Tibetisch' },
  { code: 'sla', term: '', alpha2: '', en: ['Slavic languages'], de: 'Slawisch' },
  { code: 'slo', term: 'slk', alpha2: 'sk', en: ['Slovak'], de: 'Slowakisch' },
  { code: 'slv', term: '', alpha2: 'sl', en: ['Slovenian'], de: 'Slowenisch' },
  { code: 'sma', term: '', alpha2: '', en: ['Southern Sami'], de: 'Südsamisch' },
  { code: 'sme', term: '', alpha2: 'se', en: ['Northern Sami'], de: 'Nordsamisch' },
  { code: 'smi', term: '', alpha2: '', en: ['Sami languages'], de: 'samische Sprachen' },
  { code: 'smj', term: '', alpha2: '', en: ['Lule Sami'], de: 'Lulesamisch' },
  { code: 'smn', term: '', alpha2: '', en: ['Inari Sami'], de: 'Inarisamisch' },
  { code: 'smo', term: '', alpha2: 'sm', en: ['Samoan'], de: 'Samoanisch' },
  { code: 'sms', term: '', alpha2: '', en: ['Skolt Sami'], de: 'Skoltsamisch' },
  { code: 'sna', term: '', alpha2: 'sn', en: ['Shona'], de: 'Shona' },
  { code: 'snd', term: '', alpha2: 'sd', en: ['Sindhi'], de: 'Sindhi' },
  { code: 'snk', term: '', alpha2: '', en: ['Soninke'], de: 'Soninke' },
  { code: 'sog', term: '', alpha2: '', en: ['Sogdian'], de: 'Sogdisch' },
  { code: 'som', term: '', alpha2: 'so', en: ['Somali'], de: 'Somali' },
  { code: 'son', term: '', alpha2: '', en: ['Songhai languages'], de: 'Songhai-Sprachen' },
  { code: 'sot', term: '', alpha2: 'st', en: ['Sotho, Southern'], de: 'Sesotho' },
  { code: 'spa', term: '', alpha2: 'es', en: ['Spanish', 'Castilian'], de: 'Spanisch' },
  { code: 'srd', term: '', alpha2: 'sc', en: ['Sardinian'], de: 'Sardisch' },
  { code: 'srn', term: '', alpha2: '', en: ['Sranan Tongo'], de: 'Sranantongo' },
  { code: 'srp', term: '', alpha2: 'sr', en: ['Serbian'], de: 'Serbisch' },
  { code: 'srr', term: '', alpha2: '', en: ['Serer'], de: 'Serer' },
  { code: 'ssa', term: '', alpha2: '', en: ['Nilo-Saharan languages'], de: 'Nilosaharanisch' },
  { code: 'ssw', term: '', alpha2: 'ss', en: ['Swati'], de: 'Siswati' },
  { code: 'suk', term: '', alpha2: '', en: ['Sukuma'], de: 'Sukuma' },
  { code: 'sun', term: '', alpha2: 'su', en: ['Sundanese'], de: 'Sundanesisch' },
  { code: 'sus', term: '', alpha2: '', en: ['Susu'], de: 'Susu' },
  { code: 'sux', term: '', alpha2: '', en: ['Sumerian'], de: 'Sumerisch' },
  { code: 'swa', term: '', alpha2: 'sw', en: ['Swahili'], de: 'Swahili' },
  { code: 'swe', term: '', alpha2: 'sv', en: ['Swedish'], de: 'Schwedisch' },
  { code: 'syc', term: '', alpha2: '', en: ['Classical Syriac'], de: 'Syrisch' },
  { code: 'syr', term: '', alpha2: '', en: ['Syriac'], de: '' },
  { code: 'tah', term: '', alpha2: 'ty', en: ['Tahitian'], de: 'Tahitianisch' },
  { code: 'tai', term: '', alpha2: '', en: ['Tai languages'], de: 'Tai' },
  { code: 'tam', term: '', alpha2: 'ta', en: ['Tamil'], de: 'Tamil' },
  { code: 'tat', term: '', alpha2: 'tt', en: ['Tatar'], de: 'Tatarisch' },
  { code: 'tel', term: '', alpha2: 'te', en: ['Telugu'], de: 'Telugu' },
  { code: 'tem', term: '', alpha2: '', en: ['Timne'], de: 'Temne' },
  { code: 'ter', term: '', alpha2: '', en: ['Tereno'], de: 'Terêna' },
  { code: 'tet', term: '', alpha2: '', en: ['Tetum'], de: 'Tetum' },
  { code: 'tgk', term: '', alpha2: 'tg', en: ['Tajik'], de: 'Tadschikisch' },
  { code: 'tgl', term: '', alpha2: 'tl', en: ['Tagalog'], de: '' },
  { code: 'tha', term: '', alpha2: 'th', en: ['Thai'], de: 'Thailändisch' },
  { code: 'tib', term: 'bod', alpha2: 'bo', en: ['Tibetan'], de: 'Tibetisch' },
  { code: 'tig', term: '', alpha2: '', en: ['Tigre'], de: 'Tigre' },
  { code: 'tir', term: '', alpha2: 'ti', en: ['Tigrinya'], de: 'Tigrinya' },
  { code: 'tiv', term: '', alpha2: '', en: ['Tiv'], de: 'Tiv' },
  { code: 'tkl', term: '', alpha2: '', en: ['Tokelau'], de: 'Tokelauisch' },
  { code: 'tlh', term: '', alpha2: '', en: ['Klingon', 'tlhIngan-Hol'], de: 'Klingonisch' },
  { code: 'tli', term: '', alpha2: '', en: ['Tlingit'], de: 'Tlingit' },
  { code: 'tmh', term: '', alpha2: '', en: ['Tamashek'], de: 'Tuareg' },
  { code: 'tog', term: '', alpha2: '', en: ['Tonga (Nyasa)'], de: 'Tonga' },
  { code: 'ton', term: '', alpha2: 'to', en: ['Tonga (Tonga Islands)'], de: 'Tongaisch' },
  { code: 'tpi', term: '', alpha2: '', en: ['Tok Pisin'], de: 'Tok Pisin' },
  { code: 'tsi', term: '', alpha2: '', en: ['Tsimshian'], de: 'Tsimshian' },
  { code: 'tsn', term: '', alpha2: 'tn', en: ['Tswana'], de: 'Setswana' },
  { code: 'tso', term: '', alpha2: 'ts', en: ['Tsonga'], de: 'Xitsonga' },
  { code: 'tuk', term: '', alpha2: 'tk', en: ['Turkmen'], de: 'Turkmenisch' },
  { code: 'tum', term: '', alpha2: '', en: ['Tumbuka'], de: 'Tumbuka' },
  { code: 'tup', term: '', alpha2: '', en: ['Tupi languages'], de: 'Tupí-Sprachen' },
  { code: 'tur', term: '', alpha2: 'tr', en: ['Turkish'], de: 'Türkisch' },
  { code: 'tut', term: '', alpha2: '', en: ['Altaic languages'], de: 'Altaisch' },
  { code: 'tvl', term: '', alpha2: '', en: ['Tuvalu'], de: 'Tuvaluisch' },
  { code: 'twi', term: '', alpha2: 'tw', en: ['Twi'], de: 'Twi' },
  { code: 'tyv', term: '', alpha2: '', en: ['Tuvinian'], de: 'Tuwinisch' },
  { code: 'udm', term: '', alpha2: '', en: ['Udmurt'], de: 'Udmurtisch' },
  { code: 'uga', term: '', alpha2: '', en: ['Ugaritic'], de: 'Ugaritisch' },
  { code: 'uig', term: '', alpha2: 'ug', en: ['Uighur', 'Uyghur'], de: 'Uigurisch' },
  { code: 'ukr', term: '', alpha2: 'uk', en: ['Ukrainian'], de: 'Ukrainisch' },
  { code: 'umb', term: '', alpha2: '', en: ['Umbundu'], de: 'Umbundu' },
  { code: 'und', term: '', alpha2: '', en: ['Undetermined'], de: 'unbestimmte Sprache' },
  { code: 'urd', term: '', alpha2: 'ur', en: ['Urdu'], de: 'Urdu' },
  { code: 'uzb', term: '', alpha2: 'uz', en: ['Uzbek'], de: 'Usbekisch' },
  { code: 'vai', term: '', alpha2: '', en: ['Vai'], de: 'Vai' },
  { code: 'ven', term: '', alpha2: 've', en: ['Venda'], de: 'Tshivenda' },
  { code: 'vie', term: '', alpha2: 'vi', en: ['Vietnamese'], de: 'Vietnamesisch' },
  { code: 'vol', term: '', alpha2: 'vo', en: ['Volapük'], de: 'Volapük' },
  { code: 'vot', term: '', alpha2: '', en: ['Votic'], de: 'Wotisch' },
  { code: 'wak', term: '', alpha2: '', en: ['Wakashan languages'], de: 'Wakash-Sprachen' },
  { code: 'wal', term: '', alpha2: '', en: ['Wolaitta', 'Wolaytta'], de: 'Wolaytta' },
  { code: 'war', term: '', alpha2: '', en: ['Waray'], de: 'Wáray-Wáray' },
  { code: 'was', term: '', alpha2: '', en: ['Washo'], de: 'Washoe' },
  { code: 'wel', term: 'cym', alpha2: 'cy', en: ['Welsh'], de: 'Walisisch' },
  { code: 'wen', term: '', alpha2: '', en: ['Sorbian languages'], de: 'Sorbisch' },
  { code: 'wln', term: '', alpha2: 'wa', en: ['Walloon'], de: 'Wallonisch' },
  { code: 'wol', term: '', alpha2: 'wo', en: ['Wolof'], de: 'Wolof' },
  { code: 'xal', term: '', alpha2: '', en: ['Kalmyk', 'Oirat'], de: 'Oiratisch' },
  { code: 'xho', term: '', alpha2: 'xh', en: ['Xhosa'], de: 'IsiXhosa' },
  { code: 'yao', term: '', alpha2: '', en: ['Yao'], de: 'Yao' },
  { code: 'yap', term: '', alpha2: '', en: ['Yapese'], de: 'Yapesisch' },
  { code: 'yid', term: '', alpha2: 'yi', en: ['Yiddish'], de: 'Jiddisch' },
  { code: 'yor', term: '', alpha2: 'yo', en: ['Yoruba'], de: 'Yoruba' },
  { code: 'ypk', term: '', alpha2: '', en: ['Yupik languages'], de: 'Yupik-Sprachen' },
  { code: 'zap', term: '', alpha2: '', en: ['Zapotec'], de: 'Zapotekisch' },
  { code: 'zbl', term: '', alpha2: '', en: ['Blissymbols', 'Blissymbolics', 'Bliss'], de: 'Bliss-Symbol' },
  { code: 'zen', term: '', alpha2: '', en: ['Zenaga'], de: 'Zenaga' },
  { code: 'zgh', term: '', alpha2: '', en: ['Standard Moroccan Tamazight'], de: 'marokkanisches Amazigh' },
  { code: 'zha', term: '', alpha2: 'za', en: ['Zhuang', 'Chuang'], de: 'Zhuang' },
  { code: 'znd', term: '', alpha2: '', en: ['Zande languages'], de: 'Zande-Sprachen' },
  { code: 'zul', term: '', alpha2: 'zu', en: ['Zulu'], de: 'isiZulu' },
  { code: 'zun', term: '', alpha2: '', en: ['Zuni'], de: 'Zuñi' },
  { code: 'zxx', term: '', alpha2: '', en: ['No linguistic content', 'Not applicable'], de: 'kein sprachlicher Inhalt' },
  { code: 'zza', term: '', alpha2: '', en: ['Zaza', 'Dimili', 'Dimli', 'Kirdki', 'Kirmanjki', 'Zazaki'], de: 'Zaza-Sprache' },
]
